use cs3380; 

CREATE TABLE part_category(
   category_id INTEGER  NOT NULL PRIMARY KEY 
  ,name        VARCHAR(44) NOT NULL);
INSERT INTO part_category(category_id,name) VALUES (1,'Baseplates');
INSERT INTO part_category(category_id,name) VALUES (3,'Bricks Sloped');
INSERT INTO part_category(category_id,name) VALUES (4,'Duplo, Quatro and Primo');
INSERT INTO part_category(category_id,name) VALUES (5,'Bricks Special');
INSERT INTO part_category(category_id,name) VALUES (6,'Bricks Wedged');
INSERT INTO part_category(category_id,name) VALUES (7,'Containers');
INSERT INTO part_category(category_id,name) VALUES (8,'Technic Bricks');
INSERT INTO part_category(category_id,name) VALUES (9,'Plates Special');
INSERT INTO part_category(category_id,name) VALUES (11,'Bricks');
INSERT INTO part_category(category_id,name) VALUES (12,'Technic Connectors');
INSERT INTO part_category(category_id,name) VALUES (13,'Minifigs');
INSERT INTO part_category(category_id,name) VALUES (14,'Plates');
INSERT INTO part_category(category_id,name) VALUES (15,'Tiles Special');
INSERT INTO part_category(category_id,name) VALUES (16,'Windows and Doors');
INSERT INTO part_category(category_id,name) VALUES (17,'Non-LEGO');
INSERT INTO part_category(category_id,name) VALUES (18,'Hinges, Arms and Turntables');
INSERT INTO part_category(category_id,name) VALUES (19,'Tiles');
INSERT INTO part_category(category_id,name) VALUES (20,'Bricks Round and Cones');
INSERT INTO part_category(category_id,name) VALUES (21,'Plates Round Curved and Dishes');
INSERT INTO part_category(category_id,name) VALUES (22,'Pneumatics');
INSERT INTO part_category(category_id,name) VALUES (23,'Panels');
INSERT INTO part_category(category_id,name) VALUES (24,'Other');
INSERT INTO part_category(category_id,name) VALUES (25,'Technic Steering, Suspension and Engine');
INSERT INTO part_category(category_id,name) VALUES (26,'Technic Special');
INSERT INTO part_category(category_id,name) VALUES (27,'Minifig Accessories');
INSERT INTO part_category(category_id,name) VALUES (28,'Plants and Animals');
INSERT INTO part_category(category_id,name) VALUES (29,'Wheels and Tyres');
INSERT INTO part_category(category_id,name) VALUES (30,'Tubes and Hoses');
INSERT INTO part_category(category_id,name) VALUES (31,'String, Bands and Reels');
INSERT INTO part_category(category_id,name) VALUES (32,'Bars, Ladders and Fences');
INSERT INTO part_category(category_id,name) VALUES (33,'Rock');
INSERT INTO part_category(category_id,name) VALUES (34,'Supports, Girders and Cranes');
INSERT INTO part_category(category_id,name) VALUES (35,'Transportation - Sea and Air');
INSERT INTO part_category(category_id,name) VALUES (36,'Transportation - Land');
INSERT INTO part_category(category_id,name) VALUES (37,'Bricks Curved');
INSERT INTO part_category(category_id,name) VALUES (38,'Flags, Signs, Plastics and Cloth');
INSERT INTO part_category(category_id,name) VALUES (39,'Magnets and Holders');
INSERT INTO part_category(category_id,name) VALUES (40,'Technic Panels');
INSERT INTO part_category(category_id,name) VALUES (41,'Large Buildable Figures');
INSERT INTO part_category(category_id,name) VALUES (42,'Belville, Scala and Fabuland');
INSERT INTO part_category(category_id,name) VALUES (43,'Znap');
INSERT INTO part_category(category_id,name) VALUES (44,'Mechanical');
INSERT INTO part_category(category_id,name) VALUES (45,'Electronics');
INSERT INTO part_category(category_id,name) VALUES (46,'Technic Axles');
INSERT INTO part_category(category_id,name) VALUES (47,'Windscreens and Fuselage');
INSERT INTO part_category(category_id,name) VALUES (48,'Clikits');
INSERT INTO part_category(category_id,name) VALUES (49,'Plates Angled');
INSERT INTO part_category(category_id,name) VALUES (50,'HO Scale');
INSERT INTO part_category(category_id,name) VALUES (51,'Technic Beams');
INSERT INTO part_category(category_id,name) VALUES (52,'Technic Gears');
INSERT INTO part_category(category_id,name) VALUES (53,'Technic Pins');
INSERT INTO part_category(category_id,name) VALUES (54,'Technic Bushes');
INSERT INTO part_category(category_id,name) VALUES (55,'Technic Beams Special');
INSERT INTO part_category(category_id,name) VALUES (56,'Tools');
INSERT INTO part_category(category_id,name) VALUES (57,'Non-Buildable Figures (Duplo, Fabuland, etc)');
INSERT INTO part_category(category_id,name) VALUES (58,'Stickers');
INSERT INTO part_category(category_id,name) VALUES (59,'Minifig Heads');
INSERT INTO part_category(category_id,name) VALUES (60,'Minifig Upper Body');
INSERT INTO part_category(category_id,name) VALUES (61,'Minifig Lower Body');
INSERT INTO part_category(category_id,name) VALUES (62,'Minidoll Heads');
INSERT INTO part_category(category_id,name) VALUES (63,'Minidoll Upper Body');
INSERT INTO part_category(category_id,name) VALUES (64,'Minidoll Lower Body');
INSERT INTO part_category(category_id,name) VALUES (65,'Minifig Headwear');
INSERT INTO part_category(category_id,name) VALUES (66,'Modulex');
INSERT INTO part_category(category_id,name) VALUES (67,'Tiles Round and Curved');
INSERT INTO part_category(category_id,name) VALUES (68,'Projectiles / Launchers');
